const Action = {
  CREATE_EVENT: "CREATE_EVENT",
  UPDATE_EVENT: "UPDATE_EVENT",
  CREATE_SUPPLIER: "CREATE_SUPPLIER",
  ADD_BUYER_TO_EVENT: "ADD_BUYER_TO_EVENT",
  CONSUME_EVENT: "CONSUME_EVENT",
};

module.exports = Action;
